"""initial schema

Revision ID: 3b3a1b0d6d02
Revises: 
Create Date: 2026-06-13 22:03:34.321098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3a1b0d6d02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('anon_session_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PARSING', 'DISCOVERING', 'ENRICHING', 'SCORING', 'RANKING', 'DONE', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('university_url', sa.String(), nullable=False),
    sa.Column('research_interests', sa.Text(), nullable=False),
    sa.Column('cv_text', sa.Text(), nullable=False),
    sa.Column('student_profile', sa.JSON(), nullable=True),
    sa.Column('faculty', sa.JSON(), nullable=True),
    sa.Column('enriched', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('total_analyzed', sa.Integer(), nullable=True),
    sa.Column('processing_seconds', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_jobs_anon_session_id'), 'match_jobs', ['anon_session_id'], unique=False)
    op.create_index(op.f('ix_match_jobs_user_id'), 'match_jobs', ['user_id'], unique=False)
    op.create_table('promo_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('credit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('GRANT_SIGNUP', 'GRANT_REGEN', 'GRANT_PROMO', 'GRANT_PURCHASE', 'GRANT_REFUND', 'GRANT_ADMIN', 'SPEND_SEARCH', name='crediteventtype'), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_events_user_id'), 'credit_events', ['user_id'], unique=False)
    op.create_index('ix_credit_user_created', 'credit_events', ['user_id', 'created_at'], unique=False)
    op.create_table('promo_redemptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('promo_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_id', 'user_id', name='uq_promo_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_redemptions')
    op.drop_index('ix_credit_user_created', table_name='credit_events')
    op.drop_index(op.f('ix_credit_events_user_id'), table_name='credit_events')
    op.drop_table('credit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_match_jobs_user_id'), table_name='match_jobs')
    op.drop_index(op.f('ix_match_jobs_anon_session_id'), table_name='match_jobs')
    op.drop_table('match_jobs')
    # ### end Alembic commands ###
